spring:
  main:
    allow-bean-definition-overriding: 'true'
    allow-circular-references: 'true'
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${spring.jpa.username}
    password: ${spring.jpa.password}
    driver: org.postgresql.Driver
    depends-on: entityManagerFactory
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          password: ${spring.jpa.password}
          username: ${spring.jpa.username}
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: 'false'
  sql:
    init:
      mode: always
  datasource:
    continue-on-error: 'true'
    driver: org.postgresql.Driver
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    url: jdbc:postgresql://localhost:6432/gym_dev
    initialize: 'true'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    memory:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.index.html
  api-docs:
    path: /api-docs
logging:
  level:
    org:
      springframework:
        security: trace
  pattern:
    level: '%5p %mdc'
jwt:
  access:
    token:
      expiration: '1800000'
  refresh:
    token:
      expiration: '2880000'
server:
  port: '8888'
  servlet:
    context-path: /
security:
  login:
    block:
      attempts: '3'
      duration:
        minutes: '5'
    superuser:
      username: ${superuser.username}
      password: ${superuser.password}
resilience4j.circuitbreaker:
  instances:
    update:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException
      ignoreExceptions: