spring:
  jpa:
    properties:
      hibernate:
        connection:
          url: jdbc:postgresql://gym_postgres:6432/gym_prod
  flyway:
    url: jdbc:postgresql://gym_postgres:6432/gym_prod

jms:
  trainer-working-hours-queue: trainer.working.hours.queue.prod

springdoc:
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  metrics:
    export:
      prometheus:
        enabled: false
