spring:
  jpa:
    properties:
      hibernate:
        connection:
          url: jdbc:postgresql://postgres:5432/gym_stg
  flyway:
    url: jdbc:postgresql://postgres:5432/gym_stg

jms:
  trainer-working-hours-queue: trainer.working.hours.queue.stg