server:
  port:
    8881

spring:
  application:
    name: trainer-working-hours-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}
      authentication-database: ${mongodb.authentication_database}
      uri: mongodb://localhost:27017/${mongodb.database}