server:
  port:
    8881

spring:
  application:
    name: trainer-working-hours-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gym
      username: admin
      password: password
      authentication-database: admin
      uri: mongodb://localhost:27017/gym